/-
Copyright (c) 2025 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne, Paulo Rauber
-/
module

public import LeanMachineLearning.SequentialLearning.Algorithm

/-!
# Probability space for algorithm-environment interactions

For any algorithm and environment, we construct a probability space on which we can define
a sequence of random variables representing the actions and feedback generated by the interaction
of the algorithm and the environment.
The main ingredient of the construction is the Ionescu-Tulcea theorem.

## Main statements

* `isAlgEnvSeq_unique`: the law of the sequence of actions and observations generated by an
  algorithm-environment pair is unique: it does not depend on the probability space used.
  If `A₁`, `R₁` and `A₂`, `R₂` are two algorithm-environment sequences generated by the same
  algorithm-environment pair on probability spaces `(Ω, P)` and `(Ω', P')`, then
  `P.map (fun ω n ↦ (A₁ n ω, R₁ n ω)) = P'.map (fun ω n ↦ (A₂ n ω, R₂ n ω))`.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Filter Real Finset

open scoped ENNReal NNReal

namespace Learning

variable {𝓐 𝓨 Ω : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- Measure on the sequence of actions and observations generated by the algorithm/environment. -/
noncomputable
def trajMeasure (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    Measure (ℕ → 𝓐 × 𝓨) :=
  Kernel.trajMeasure (alg.p0 ⊗ₘ env.ν0) (stepKernel alg env)
deriving IsProbabilityMeasure

section ModelEquivalence

variable {Ω Ω' : Type*} {mΩ : MeasurableSpace Ω} {mΩ' : MeasurableSpace Ω'}
  [StandardBorelSpace 𝓐] [Nonempty 𝓐] [StandardBorelSpace 𝓨] [Nonempty 𝓨]
  {alg : Algorithm 𝓐 𝓨} {env : Environment 𝓐 𝓨}
  {P : Measure Ω} [IsProbabilityMeasure P] {P' : Measure Ω'} [IsProbabilityMeasure P']
  {A₁ : ℕ → Ω → 𝓐} {R₁ : ℕ → Ω → 𝓨} {A₂ : ℕ → Ω' → 𝓐} {R₂ : ℕ → Ω' → 𝓨} {N : ℕ}

theorem eq_trajMeasure_of_isAlgEnvSeq (h : IsAlgEnvSeq A₁ R₁ alg env P) :
    P.map (fun ω n ↦ (A₁ n ω, R₁ n ω)) = trajMeasure alg env := by
  rw [trajMeasure]
  have h := Kernel.eq_trajMeasure (Y := fun n ω ↦ (A₁ n ω, R₁ n ω)) (P := P)
    (μ₀ := alg.p0 ⊗ₘ env.ν0) (κ := stepKernel alg env) (fun n ↦ ?_) ?_ (fun n ↦ ?_)
  · exact h
  · have hA := h.measurable_action n
    have hR := h.measurable_feedback n
    fun_prop
  · simp only
    exact h.hasLaw_step_zero
  · exact h.hasCondDistrib_step n

lemma eq_trajMeasure_map_frestrictLe_of_isAlgEnvSeqUntil
    (h : IsAlgEnvSeqUntil A₁ R₁ alg env P N) :
    P.map (fun ω (n : Iic N) ↦ (A₁ n ω, R₁ n ω)) =
      (trajMeasure alg env).map (Preorder.frestrictLe N) := by
  rw [trajMeasure]
  have h := Kernel.eq_trajMeasure_map_frestrictLe (Y := fun n ω ↦ (A₁ n ω, R₁ n ω))
    (P := P) (μ₀ := alg.p0 ⊗ₘ env.ν0) (κ := stepKernel alg env) ?_ (fun n hn ↦ ?_) (N := N)
  · exact h
  · exact h.hasLaw_step_zero
  · exact h.hasCondDistrib_step n hn

/-- The law of the sequence of actions and observations generated by an algorithm-environment pair
is unique: it does not depend on the probability space used. -/
-- ANCHOR: isAlgEnvSeq_unique
theorem isAlgEnvSeq_unique (h1 : IsAlgEnvSeq A₁ R₁ alg env P)
    (h2 : IsAlgEnvSeq A₂ R₂ alg env P') :
    P.map (fun ω n ↦ (A₁ n ω, R₁ n ω)) = P'.map (fun ω n ↦ (A₂ n ω, R₂ n ω)) := by
-- ANCHOR_END: isAlgEnvSeq_unique
  rw [eq_trajMeasure_of_isAlgEnvSeq h1, eq_trajMeasure_of_isAlgEnvSeq h2]

/-- The law of the sequence of actions and observations generated by an algorithm-environment pair
is unique: it does not depend on the probability space used. -/
lemma IsAlgEnvSeq.identDistrib_trajectory (h1 : IsAlgEnvSeq A₁ R₁ alg env P)
    (h2 : IsAlgEnvSeq A₂ R₂ alg env P') :
    IdentDistrib (fun ω n ↦ (A₁ n ω, R₁ n ω)) (fun ω' n ↦ (A₂ n ω', R₂ n ω')) P P' where
  aemeasurable_fst := (measurable_pi_iff.2 fun n ↦ (h1.measurable_action n).prodMk
    (h1.measurable_feedback n)).aemeasurable
  aemeasurable_snd := (measurable_pi_iff.2 fun n ↦ (h2.measurable_action n).prodMk
    (h2.measurable_feedback n)).aemeasurable
  map_eq := isAlgEnvSeq_unique h1 h2

theorem isAlgEnvSeqUntil_unique (h1 : IsAlgEnvSeqUntil A₁ R₁ alg env P N)
    (h2 : IsAlgEnvSeqUntil A₂ R₂ alg env P' N) :
    P.map (fun ω (n : Iic N) ↦ (A₁ n ω, R₁ n ω)) =
      P'.map (fun ω (n : Iic N) ↦ (A₂ n ω, R₂ n ω)) := by
  rw [eq_trajMeasure_map_frestrictLe_of_isAlgEnvSeqUntil h1,
    eq_trajMeasure_map_frestrictLe_of_isAlgEnvSeqUntil h2]

end ModelEquivalence

namespace IT

/-- Action and feedback at step `n`. -/
def step (n : ℕ) (h : ℕ → 𝓐 × 𝓨) : 𝓐 × 𝓨 := h n

/-- `action n` is the action pulled at time `n`. This is a random variable on the measurable space
`ℕ → 𝓐 × 𝓨`. -/
def action (n : ℕ) (h : ℕ → 𝓐 × 𝓨) : 𝓐 := (h n).1

/-- `feedback n` is the feedback at time `n`. This is a random variable on the measurable space
`ℕ → 𝓐 × 𝓨`. -/
def feedback (n : ℕ) (h : ℕ → 𝓐 × 𝓨) : 𝓨 := (h n).2

/-- `hist n` is the history up to time `n`. This is a random variable on the measurable space
`ℕ → 𝓐 × 𝓨`. -/
def hist (n : ℕ) (h : ℕ → 𝓐 × 𝓨) : Iic n → 𝓐 × 𝓨 := fun i ↦ h i

lemma fst_comp_step (n : ℕ) : Prod.fst ∘ step (𝓐 := 𝓐) (𝓨 := 𝓨) n = action n := rfl

@[fun_prop]
lemma measurable_step (n : ℕ) : Measurable (step n (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold step; fun_prop

@[fun_prop]
lemma measurable_step_prod : Measurable (fun p : ℕ × (ℕ → 𝓐 × 𝓨) ↦ step p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_action (n : ℕ) : Measurable (action n (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold action; fun_prop

@[fun_prop]
lemma measurable_action_prod : Measurable (fun p : ℕ × (ℕ → 𝓐 × 𝓨) ↦ action p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_feedback (n : ℕ) : Measurable (feedback n (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold feedback; fun_prop

@[fun_prop]
lemma measurable_feedback_prod : Measurable (fun p : ℕ × (ℕ → 𝓐 × 𝓨) ↦ feedback p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_hist (n : ℕ) : Measurable (hist n (𝓐 := 𝓐) (𝓨 := 𝓨)) := by unfold hist; fun_prop

lemma hist_eq_frestrictLe :
    hist = Preorder.frestrictLe («π» := fun _ ↦ 𝓐 × 𝓨) := by
  ext n h i : 3
  simp [hist, Preorder.frestrictLe]

/-- Filtration of the algorithm Seq. -/
protected def filtration (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] :
    Filtration ℕ (inferInstance : MeasurableSpace (ℕ → 𝓐 × 𝓨)) :=
  MeasureTheory.Filtration.piLE (X := fun _ ↦ 𝓐 × 𝓨)

lemma filtration_eq_comap (n : ℕ) :
    IT.filtration 𝓐 𝓨 n = MeasurableSpace.comap (hist n) inferInstance := by
  simp [IT.filtration, Filtration.piLE_eq_comap_frestrictLe, ← hist_eq_frestrictLe]

lemma step_eq_eval_comp_hist (n : ℕ) :
    step (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ x ⟨n, by simp⟩) ∘ (hist n) := rfl

lemma action_eq_eval_comp_hist (n : ℕ) :
    action (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ (x ⟨n, by simp⟩).1) ∘ (hist n) := rfl

lemma feedback_eq_eval_comp_hist (n : ℕ) :
    feedback (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ (x ⟨n, by simp⟩).2) ∘ (hist n) := rfl

lemma adapted_step : Adapted (IT.filtration 𝓐 𝓨) (step (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  intro n
  rw [filtration_eq_comap, step_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_hist : Adapted (IT.filtration 𝓐 𝓨) hist := by
  intro n
  simp [filtration_eq_comap, measurable_iff_comap_le]

lemma adapted_action : Adapted (IT.filtration 𝓐 𝓨) action := by
  intro n
  rw [filtration_eq_comap, action_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_feedback : Adapted (IT.filtration 𝓐 𝓨) feedback := by
  intro n
  rw [filtration_eq_comap, feedback_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

section FiltrationAction

/-- Filtration generated by the history at time `n-1` together with the action at time `n`. -/
def filtrationAction (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] :
    Filtration ℕ (inferInstance : MeasurableSpace (ℕ → 𝓐 × 𝓨)) where
  seq n := if n = 0 then MeasurableSpace.comap (action 0) inferInstance
    else IT.filtration 𝓐 𝓨 (n - 1) ⊔ MeasurableSpace.comap (action n) inferInstance
  mono' n m hnm := by
    simp only
    by_cases hn : n = 0
    · by_cases hm : m = 0
      · simp [hn, hm]
      · simp only [hn, ↓reduceIte, hm]
        refine le_sup_of_le_left ?_
        rw [← measurable_iff_comap_le]
        suffices Measurable[IT.filtration 𝓐 𝓨 0] (action 0) from
          this.mono ((IT.filtration 𝓐 𝓨).mono zero_le') le_rfl
        exact adapted_action 0
    have hm : m ≠ 0 := by grind
    simp only [hn, hm, ↓reduceIte]
    have hnm' : n - 1 ≤ m - 1 := by grind
    simp only [sup_le_iff]
    constructor
    · refine le_sup_of_le_left ?_
      exact (IT.filtration 𝓐 𝓨).mono hnm'
    · rcases eq_or_lt_of_le hnm with rfl | hlt
      · exact le_sup_of_le_right le_rfl
      refine le_sup_of_le_left ?_
      rw [← measurable_iff_comap_le]
      have h_le : n ≤ m - 1 := by grind
      suffices Measurable[IT.filtration 𝓐 𝓨 n] (action n) from
        this.mono ((IT.filtration 𝓐 𝓨).mono h_le) le_rfl
      exact adapted_action n
  le' n := by
    by_cases hn : n = 0
    · simp only [hn, ↓reduceIte]
      rw [← measurable_iff_comap_le]
      fun_prop
    simp only [hn, ↓reduceIte, sup_le_iff]
    constructor
    · exact (IT.filtration 𝓐 𝓨).le _
    · rw [← measurable_iff_comap_le]
      fun_prop

lemma filtrationAction_zero_eq_comap :
    filtrationAction 𝓐 𝓨 0 = MeasurableSpace.comap (action 0) inferInstance := by
  simp [filtrationAction]

lemma filtrationAction_eq_comap (n : ℕ) (hn : n ≠ 0) :
    filtrationAction 𝓐 𝓨 n =
      MeasurableSpace.comap (fun ω ↦ (hist (n - 1) ω, action n ω)) inferInstance := by
  simp only [filtrationAction, filtration_eq_comap, ← MeasurableSpace.comap_prodMk, hn, ↓reduceIte]
  rfl

lemma filtration_le_filtrationAction_add_one (n : ℕ) :
    IT.filtration 𝓐 𝓨 n ≤ filtrationAction 𝓐 𝓨 (n + 1) := le_sup_of_le_left le_rfl

lemma filtration_le_filtrationAction {m n : ℕ} (h : n < m) :
    IT.filtration 𝓐 𝓨 n ≤ filtrationAction 𝓐 𝓨 m := by
  have h' : n + 1 ≤ m := by grind
  exact (filtration_le_filtrationAction_add_one n).trans ((filtrationAction 𝓐 𝓨).mono h')

lemma filtrationAction_le_filtration_self (n : ℕ) :
    filtrationAction 𝓐 𝓨 n ≤ IT.filtration 𝓐 𝓨 n := by
  by_cases hn : n = 0
  · simp only [hn, filtrationAction_zero_eq_comap]
    rw [← measurable_iff_comap_le]
    exact adapted_action 0
  simp only [filtrationAction, hn, ↓reduceIte, sup_le_iff]
  constructor
  · exact (IT.filtration 𝓐 𝓨).mono (by grind)
  · rw [← measurable_iff_comap_le]
    exact adapted_action _

lemma filtrationAction_le_filtration {m n : ℕ} (h : m ≤ n) :
    filtrationAction 𝓐 𝓨 m ≤ IT.filtration 𝓐 𝓨 n :=
  (filtrationAction_le_filtration_self m).trans ((IT.filtration 𝓐 𝓨).mono h)

lemma measurable_action_filtrationAction (n : ℕ) :
    Measurable[filtrationAction 𝓐 𝓨 n] (action n) := by
  rw [measurable_iff_comap_le]
  simp only [filtrationAction]
  split_ifs with hn
  · simp [hn]
  · exact le_sup_of_le_right le_rfl

end FiltrationAction

section Laws

lemma hasLaw_step_zero (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    HasLaw (step 0) (alg.p0 ⊗ₘ env.ν0) (trajMeasure alg env) where
  aemeasurable := Measurable.aemeasurable (by fun_prop)
  map_eq := by
    unfold step
    rw [← coe_default_Iic_zero]
    simp only [trajMeasure, Kernel.trajMeasure]
    rw [← Measure.deterministic_comp_eq_map (by fun_prop), Measure.comp_assoc,
      Kernel.deterministic_comp_eq_map, Kernel.traj_zero_map_eval_zero,
      Measure.deterministic_comp_eq_map, Measure.map_map (by fun_prop) (by fun_prop)]
    exact Measure.map_id

lemma hasLaw_action_zero (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    HasLaw (action 0) alg.p0 (trajMeasure alg env) where
  map_eq := by
    rw [← fst_comp_step, ← Measure.map_map (by fun_prop) (by fun_prop),
      (hasLaw_step_zero alg env).map_eq, ← Measure.fst, Measure.fst_compProd]

variable [StandardBorelSpace 𝓨] [Nonempty 𝓨]

lemma condDistrib_feedback_zero (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    condDistrib (feedback 0) (action 0) (trajMeasure alg env)
      =ᵐ[(trajMeasure alg env).map (action 0)] env.ν0 := by
  have h_step := (hasLaw_step_zero alg env).map_eq
  have h_action := (hasLaw_action_zero alg env).map_eq
  rwa [condDistrib_ae_eq_iff_measure_eq_compProd _ (by fun_prop), h_action]

variable [StandardBorelSpace 𝓐] [Nonempty 𝓐]

lemma condDistrib_step (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    condDistrib (step (n + 1)) (hist n) (trajMeasure alg env)
      =ᵐ[(trajMeasure alg env).map (hist n)] stepKernel alg env n :=
  Kernel.condDistrib_trajMeasure

lemma condDistrib_action (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    condDistrib (action (n + 1)) (hist n) (trajMeasure alg env)
      =ᵐ[(trajMeasure alg env).map (hist n)] alg.policy n := by
  rw [← fst_comp_step]
  refine (condDistrib_comp _ (by fun_prop) (by fun_prop)).trans ?_
  filter_upwards [condDistrib_step alg env n] with h h_eq
  rw [Kernel.map_apply _ (by fun_prop), h_eq, ← Kernel.map_apply _ (by fun_prop), ← Kernel.fst_eq,
    fst_stepKernel]

lemma condDistrib_feedback (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    condDistrib (feedback (n + 1)) (fun ω ↦ (hist n ω, action (n + 1) ω)) (trajMeasure alg env)
      =ᵐ[(trajMeasure alg env).map (fun ω ↦ (hist n ω, action (n + 1) ω))] env.feedback n := by
  have h_step := condDistrib_step alg env n
  have h_action := condDistrib_action alg env n
  rw [condDistrib_ae_eq_iff_measure_eq_compProd _ (by fun_prop)] at h_step h_action ⊢
  rw [h_action, ← Measure.compProd_assoc, ← stepKernel, ← h_step,
    Measure.map_map (by fun_prop) (by fun_prop)]
  rfl

lemma isAlgEnvSeq_trajMeasure (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    IsAlgEnvSeq action feedback alg env (trajMeasure alg env) where
  hasLaw_action_zero := hasLaw_action_zero alg env
  hasCondDistrib_feedback_zero := ⟨by fun_prop, by fun_prop, condDistrib_feedback_zero alg env⟩
  hasCondDistrib_action n := ⟨by fun_prop, by fun_prop, condDistrib_action alg env n⟩
  hasCondDistrib_feedback n := ⟨by fun_prop, by fun_prop, condDistrib_feedback alg env n⟩

end Laws

end IT

end Learning
